// packages/lib-react/src/button.tsx
import * as React from "react";

function Button(props) {
  return (
    <a
      style={{
        border: "2px solid #000",
        borderRadius: "10px",
        padding: "10px",
      }}
    >
      <span>{props.text}</span>
    </a>
  );
}

const observedButton = observer(Button);
export default observedButton;

// packages/lib-svelte/src/button.svelte
<script>
  export let text;

  function mitosis_styling(node, vars) {
    Object.entries(vars || {}).forEach(([p, v]) => {
      if (p.startsWith("--")) {
        node.style.setProperty(p, v);
      } else {
        node.style[p] = v;
      }
    });
  }
</script>

<a
  use:mitosis_styling={{
    border: "2px solid #000",
    borderRadius: "10px",
    padding: "10px",
  }}
>
  <span>{text}</span>
</a>
