// packages/lib-react/src/img.tsx
import * as React from "react";

function Image(props) {
  return (
    <img
      src={props.src}
      style={{
        display: "block",
        outline: "none",
        border: "none",
        textDecoration: "none",
        ...props.style,
      }}
      width={props.width}
      height={props.height}
      {...props.props}
    />
  );
}

export default Image;

// packages/lib-vue3/src/img.vue
<template>
  <img
    :src="src"
    :style="{
      display: 'block',
      outline: 'none',
      border: 'none',
      textDecoration: 'none',
      ...style,
    }"
    :width="width"
    :height="height"
    v-bind="$props"
  />
</template>

<script>
export default {
  name: "image",

  props: ["src", "style", "width", "height", "props"],
};
</script>
